import type { ResolvedValaxyOptions } from 'valaxy'
import type { Plugin, ResolvedConfig } from 'vite'
import type { ThemeConfig } from '../types'
import { createHash } from 'node:crypto'
import { existsSync, promises as fs } from 'node:fs'
import path from 'node:path'
import sirv from 'sirv'
import {
  isExternalWallpaperUrl,
  resolveWallpaperWebOptions,
  WALLPAPER_WEB_SW_FILENAME,
} from '../shared/wallpaper'

const SW_CACHE_PREFIX = 'arona-wallpaper'

/**
 * 判断网页壁纸目录是否为安全的站内相对路径
 */
function isSafeWallpaperDir(dir: string): boolean {
  const normalized = dir.replace(/\\/g, '/')
  return !!normalized
    && !normalized.startsWith('/')
    && !/^[a-z]:/i.test(normalized)
    && !normalized.split('/').includes('..')
}

function logInfo(message: string) {
  // eslint-disable-next-line no-console
  console.info(message)
}

/**
 * 拼接 URL 路径，避免 `//`
 */
function joinPath(base: string, sub: string): string {
  const normalizedBase = base.endsWith('/') ? base : `${base}/`
  const normalizedSub = sub.replace(/^\/+/, '')
  return `${normalizedBase}${normalizedSub}`.replace(/\/{2,}/g, '/')
}

/**
 * 递归复制目录
 */
async function copyDir(source: string, target: string): Promise<void> {
  await fs.mkdir(target, { recursive: true })
  const entries = await fs.readdir(source, { withFileTypes: true })

  await Promise.all(entries.map(async (entry) => {
    const from = path.join(source, entry.name)
    const to = path.join(target, entry.name)

    if (entry.isDirectory())
      await copyDir(from, to)
    else if (entry.isFile())
      await fs.copyFile(from, to)
  }))
}

/**
 * 统计目录文件数与总大小
 */
async function getDirStats(dir: string): Promise<{ files: number, bytes: number }> {
  let files = 0
  let bytes = 0

  async function walk(current: string) {
    const entries = await fs.readdir(current, { withFileTypes: true })
    for (const entry of entries) {
      const abs = path.join(current, entry.name)
      if (entry.isDirectory()) {
        await walk(abs)
      }
      else if (entry.isFile()) {
        files += 1
        bytes += (await fs.stat(abs)).size
      }
    }
  }

  await walk(dir)
  return { files, bytes }
}

function formatBytes(bytes: number): string {
  if (bytes < 1024)
    return `${bytes} B`
  if (bytes < 1024 * 1024)
    return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`
}

/**
 * 根据目录内文件路径 / 大小 / 修改时间生成缓存指纹
 *
 * 资源未变化时复用同一份 SW 缓存
 */
async function createCacheVersion(dir: string): Promise<string> {
  const hash = createHash('sha256')

  async function walk(current: string, relative: string) {
    const entries = (await fs.readdir(current, { withFileTypes: true }))
      .sort((a, b) => a.name.localeCompare(b.name))

    for (const entry of entries) {
      if (entry.name === WALLPAPER_WEB_SW_FILENAME)
        continue

      const abs = path.join(current, entry.name)
      const rel = relative ? `${relative}/${entry.name}` : entry.name

      if (entry.isDirectory()) {
        await walk(abs, rel)
      }
      else if (entry.isFile()) {
        const stat = await fs.stat(abs)
        hash.update(`${rel}:${stat.size}:${Math.round(stat.mtimeMs)}`)
      }
    }
  }

  await walk(dir, '')
  return hash.digest('hex').slice(0, 12)
}

/**
 * 生成 Service Worker 源码
 *
 * 仅作用于当前脚本所在目录（即网页壁纸目录）：
 * - 二次访问 cache-first
 * - Range 请求不缓存，直接走网络
 */
function createServiceWorkerSource(version: string): string {
  return `/* Auto-generated by valaxy-theme-arona. Do not edit. */
const CACHE_NAME = '${SW_CACHE_PREFIX}-${version}'
const CACHE_PREFIX = '${SW_CACHE_PREFIX}-'

self.addEventListener('install', () => {
  self.skipWaiting()
})

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys()
    await Promise.all(
      keys
        .filter(key => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME)
        .map(key => caches.delete(key)),
    )
    await self.clients.claim()
  })())
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET' || request.headers.has('range'))
    return

  const url = new URL(request.url)
  if (url.origin !== self.location.origin)
    return

  event.respondWith((async () => {
    let cache
    try {
      cache = await caches.open(CACHE_NAME)
    }
    catch {
      return fetch(request)
    }

    try {
      const cached = await cache.match(request)
      if (cached)
        return cached
    }
    catch {}

    const response = await fetch(request)
    if (response && response.status === 200 && response.type === 'basic')
      cache.put(request, response.clone()).catch(() => {})

    return response
  })())
})
`
}

/**
 * 写入 Service Worker 文件
 */
async function writeServiceWorker(targetDir: string): Promise<void> {
  const version = await createCacheVersion(targetDir)
  const source = createServiceWorkerSource(version)
  await fs.writeFile(path.join(targetDir, WALLPAPER_WEB_SW_FILENAME), source, 'utf-8')
  logInfo(`[valaxy-theme-arona] 已生成网页壁纸缓存: ${WALLPAPER_WEB_SW_FILENAME} (${version})`)
}

/**
 * 网页壁纸插件
 *
 * - dev：将 `<userRoot>/<dir>` 挂载为 `${base}${dir}` 静态目录
 * - build：将资源复制到 `dist/<dir>`
 * - 禁用时不做任何输出
 */
export function createWallpaperPlugin(options: ResolvedValaxyOptions<ThemeConfig>): Plugin {
  const web = resolveWallpaperWebOptions(options.config.themeConfig?.wallpaper)
  const userRoot = options.userRoot
  const localDir = web.enable && typeof web.dir === 'string' && isSafeWallpaperDir(web.dir)
    ? web.dir
    : ''
  const sourceDir = localDir ? path.resolve(userRoot, localDir) : ''

  let resolvedConfig: ResolvedConfig | null = null

  return {
    name: 'valaxy-theme-arona:wallpaper',

    configResolved(config) {
      resolvedConfig = config
    },

    configureServer(server) {
      if (!web.enable || !localDir || !sourceDir)
        return

      if (!existsSync(sourceDir)) {
        console.warn(`[valaxy-theme-arona] 未找到网页壁纸目录: ${sourceDir}，跳过静态挂载`)
        return
      }

      const prefix = joinPath(resolvedConfig?.base || server.config.base || '/', localDir)
      const serve = sirv(sourceDir, { dev: true, etag: true, single: false })

      server.middlewares.use((req, res, next) => {
        const rawUrl = req.url || '/'
        const queryIndex = rawUrl.indexOf('?')
        const rawPath = queryIndex === -1 ? rawUrl : rawUrl.slice(0, queryIndex)
        const search = queryIndex === -1 ? '' : rawUrl.slice(queryIndex)

        let pathname: string
        try {
          pathname = decodeURIComponent(rawPath)
        }
        catch {
          return next()
        }

        if (pathname === prefix) {
          res.statusCode = 302
          res.setHeader('Location', `${prefix}/${search}`)
          res.end()
          return
        }

        if (!pathname.startsWith(`${prefix}/`))
          return next()

        const originalUrl = req.url
        req.url = `${pathname.slice(prefix.length) || '/'}${search}`
        serve(req, res, () => {
          req.url = originalUrl
          next()
        })
      })

      logInfo(`[valaxy-theme-arona] 网页壁纸已挂载: ${prefix} -> ${sourceDir}`)
    },

    async closeBundle() {
      if (!resolvedConfig || resolvedConfig.command !== 'build' || resolvedConfig.build.ssr)
        return

      if (!web.enable || !localDir || !sourceDir)
        return

      if (!existsSync(sourceDir)) {
        console.warn(`[valaxy-theme-arona] 未找到网页壁纸目录: ${sourceDir}，跳过复制`)
        return
      }

      const outDir = path.resolve(resolvedConfig.root, resolvedConfig.build.outDir)
      const targetDir = path.resolve(outDir, localDir)

      await copyDir(sourceDir, targetDir)
      const stats = await getDirStats(targetDir)
      logInfo(`[valaxy-theme-arona] 网页壁纸已输出: ${targetDir} (${stats.files} 个文件, ${formatBytes(stats.bytes)})`)

      if (web.cache && !isExternalWallpaperUrl(web.url))
        await writeServiceWorker(targetDir)
    },
  }
}
