/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notes/': RouteRecordInfo<
      '/notes/',
      '/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/themetest': RouteRecordInfo<
      '/posts/themetest',
      '/posts/themetest',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/themetest-2': RouteRecordInfo<
      '/posts/themetest-2',
      '/posts/themetest-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/themetest-3': RouteRecordInfo<
      '/posts/themetest-3',
      '/posts/themetest-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/themetest-4': RouteRecordInfo<
      '/posts/themetest-4',
      '/posts/themetest-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/themetest-5': RouteRecordInfo<
      '/posts/themetest-5',
      '/posts/themetest-5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/themetest-6': RouteRecordInfo<
      '/posts/themetest-6',
      '/posts/themetest-6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/themetest-7': RouteRecordInfo<
      '/posts/themetest-7',
      '/posts/themetest-7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/themetest-8': RouteRecordInfo<
      '/posts/themetest-8',
      '/posts/themetest-8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    '../theme/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    '../node_modules/.pnpm/valaxy@1.0.0-rc.11_patch_ha_bf928873db5f0bfc2221140e199aac04/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/about.md': {
      routes:
        | '/about'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/notes/index.md': {
      routes:
        | '/notes/'
      views:
        | never
    }
    'pages/posts/themetest.md': {
      routes:
        | '/posts/themetest'
      views:
        | never
    }
    'pages/posts/themetest-2.md': {
      routes:
        | '/posts/themetest-2'
      views:
        | never
    }
    'pages/posts/themetest-3.md': {
      routes:
        | '/posts/themetest-3'
      views:
        | never
    }
    'pages/posts/themetest-4.md': {
      routes:
        | '/posts/themetest-4'
      views:
        | never
    }
    'pages/posts/themetest-5.md': {
      routes:
        | '/posts/themetest-5'
      views:
        | never
    }
    'pages/posts/themetest-6.md': {
      routes:
        | '/posts/themetest-6'
      views:
        | never
    }
    'pages/posts/themetest-7.md': {
      routes:
        | '/posts/themetest-7'
      views:
        | never
    }
    'pages/posts/themetest-8.md': {
      routes:
        | '/posts/themetest-8'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
